name: Firebase Distribute

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          cache: gradle


      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and Distribute
        run: ./gradlew assembleDebug appDistributionUploadDebug
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

  firebase:
    name: Run Test on Firebase Test Lab
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug

      - name: Login to Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          export_default_credentials: true
      - run: gcloud info

      - name: Run Test on Firebase Test Lab
        run: gcloud firebase test android run --type robo --app app-debug/app-debug.apk --device model=Pixel2,version=28,locale=us,orientation=portrait